recipe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('recipe/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('charts/', views.ChartsView.as_view(), name='charts'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

recipe_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipe.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    cuisine_choices = [
        ('American', 'American'),
        ('Chinese', 'Chinese'),
        ('French', 'French'),
        ('Italian', 'Italian'),
        ('Japanese', 'Japanese'),
        ('Korean', 'Korean'),
        ('Mexican', 'Mexican'),
        ('Thai', 'Thai'),
        ('Vietnamese', 'Vietnamese'),
        ('Other', 'Other')
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    time = models.IntegerField()
    cuisine = models.CharField(max_length=255, choices=cuisine_choices)
    image = models.ImageField(default="removed.png")
    ingredients = models.ManyToManyField('Ingredient', through='RecipeIngredient')

    def isValid(self):
        return self.name != "" and self.description != "" and self.time > 0  and self.cuisine != ""

    def __str__(self):
        return f"Recipe: {self.name}"

    def get_absolute_url(self):
        return f"/recipe/{self.id}/"

    def calculate_difficulty(self):
        if self.time < 10 and self.ingredients.count() < 4:
            return "Easy"
        elif self.time < 10 and self.ingredients.count() >= 4:
            return "Medium"
        elif self.time >= 10 and self.ingredients.count() < 4:
            return "Intermediate"
        elif self.time >= 10 and self.ingredients.count() >= 4:
            return "Hard"

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    unit = models.CharField(max_length=255)

    def isValid(self):
        return self.name != "" and self.unit != ""

    def __str__(self):
        return f"Ingredient: {self.name} - Unit: {self.unit}"

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def isValid(self):
        return self.recipe != "" and self.ingredient != "" and self.amount > 0

    def __str__(self):
        return f"Recipe: {self.recipe} - Ingredient: {self.ingredient} - Amount: {self.amount}"

recipe/forms.py
from django import forms

class RecipeSearchForm(forms.Form):
    query = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={"class": "form-control-lg", "placeholder": "Search for a recipe..."}), required=False)

recipe/views.py
import pandas as pd
import matplotlib.pyplot as plt

from django.shortcuts import redirect, render
from django import views
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from recipe.forms import RecipeSearchForm

from recipe.models import Recipe, RecipeIngredient
from recipe.utils import get_chart

# Create your views here.
class HomeView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipe/recipes_home.html"

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipe/recipe_detail.html"

class SearchView(LoginRequiredMixin, views.View):
    model = Recipe
    template_name = "recipe/search.html"

    def get(self, request):
        query = request.GET.get("query")
        form  = RecipeSearchForm()
        if not query:
            recipes = Recipe.objects.all()
        else:
            recipes = Recipe.objects.filter(name__icontains=query).all()

        df = pd.DataFrame(recipes.values())


        if not df.empty:
            df.columns = df.columns.str.title()
            table_html = '<table class="table table-striped table-dark table-hover mt-5">'
            table_html += '<thead><tr><th>Name</th><th>Description</th><th>Cuisine</th><th>Time</th></tr></thead>'
            table_html += '<tbody>'
            for index, row in df.iterrows():
                table_html += '<tr>'
                table_html += f'<td><a href="{reverse("recipe_detail", args=[row["Id"]])}" class="link-warning">{row["Name"]}</a></td>'
                table_html += f'<td>{row["Description"]}</td>'
                table_html += f'<td>{row["Cuisine"]}</td>'
                table_html += f'<td>{row["Time"]}</td>'
                table_html += '</tr>'
            table_html += '</tbody></table>'
            return render(request, "recipe/search.html", {"recipes": table_html, "form": form})
        else:
            return render(request, "recipe/search.html", {"form": form, "error_message": "No results found"})

class ChartsView(LoginRequiredMixin, views.View):
    template_name = "recipe/charts.html"

    def get(self, request):
        plt.switch_backend('AGG')
        fig=plt.figure(figsize=(6,3))

        # Create pie chart of the cuisines
        recipes = Recipe.objects.all()
        df = pd.DataFrame(recipes.values())
        df = df["cuisine"].value_counts()
        plt.pie(df, labels=df.index, autopct='%1.1f%%')

        pie_chart = get_chart()
        plt.clf()

        # Create a bar chart of the ingredients in all recipes
        # recipes = RecipeIngredient.objects.all().values("ingredient_id")
        # df = pd.DataFrame(recipes.values())
        # df = df["ingredient_id"].value_counts()
        plt.bar(df.index, df)

        bar_chart = get_chart()
        plt.clf()

        # Create a line chart of the time it takes to make each recipe
        # recipes = Recipe.objects.all()
        # df = pd.DataFrame(recipes.values())
        # df = df["time"].value_counts().sort_index()
        df = df.sort_index()
        plt.plot(df.index, df)

        line_chart = get_chart()
        plt.clf()

        return render(request, "recipe/charts.html", {
            "pie_chart": pie_chart,
            "bar_chart": bar_chart,
            "line_chart": line_chart

        })

class LoginView(views.View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, "recipe/login.html", {"form": form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        error = None
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(request.GET["next"] if "next" in request.GET else "home")
            else:
                error = "Invalid username or password"

        else:
            error = "Invalid username or password"
        return render(request, "recipe/login.html", {"form": form, "error": error})

class LogoutView(views.View):
    def get(self, request):
        logout(request)
        return render(request, "recipe/success.html")

recipe/templates/recipe/charts.html
{% extends 'recipe/layout.html' %}

{% block title %} Charts {% endblock %}

{% block content %}
    <h1 class="text-center text-light">Charts</h1>
        <div class="text-light mt-3 text-center card p-3">
            <h2>Pie Chart</h2>
            <img src="data:image/png;base64, {{pie_chart|safe}}">
        </div>
        <div class="text-light mt-3 text-center card p-3">
            <h2>Bar Chart</h2>
            <img src="data:image/png;base64, {{bar_chart|safe}}">
        </div>
        <div class="text-light mt-3 text-center card p-3">
            <h2>Line Chart</h2>
            <img src="data:image/png;base64, {{line_chart|safe}}">
        </div>
{% endblock %}

recipe/templates/recipe/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recipe App - 
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background: url({% static 'background.jpg' %});">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand text-light" href="/">Recipe App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse">
            <div class="navbar-nav me-auto">
              {% if request.user.is_authenticated %}
                <a class="nav-link text-light" aria-current="page" href="{% url 'search' %}">Search</a>
                <a class="nav-link text-light" aria-current="page" href="{% url 'charts' %}">Charts</a>
              {% endif %}
            </div>
            <div class="navbar-nav">
              {% if request.user.is_authenticated %}
                <a class="nav-link text-light" aria-current="page"> Welcome {{ request.user }}!</a>
                <a class="nav-link text-light" aria-current="page" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-link text-light" aria-current="page" href="{% url 'login' %}">Login</a>
                <a class="nav-link text-light" aria-current="page" href="#">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

        <div class="container-fluid justify-content-center align-items-center d-grid">
            {% block content %}
            {% endblock %}
        </div>
</body>
</html>

recipe/templates/recipe/login.html
{% extends 'recipe/layout.html' %}


{% block title %} Login {% endblock %}

{% block content %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <h1 class="text-light mt-2">Login</h1>

    <div class="login-form m-3 p-3">
        <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
    </div>

{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends 'recipe/layout.html' %}
{% load static %}
{% load multiply %}

{% block title%}
    Detail
{% endblock %}

{% block content %}

    <div class="recipe-detail text-light mt-5">
        <h1 class="text-center">{{ object.name }}</h1>
        <img src="{{ object.image.url }}" alt="{{ object.title }}" class="border border-warning mb-4">
        <h3>
            Description:
        </h3>
        <p>{{ object.description }}</p>
        <br>
        <h3>
            Difficulty:
        </h3>
        <p>{{ object.calculate_difficulty }}</p>
        <br>
        <h3>
            Ingredients:
        </h3>
        {% for recipe_ingredient in object.recipeingredient_set.all %}
            <p>{{ recipe_ingredient.ingredient.name }}: {{ recipe_ingredient.amount }} {{ recipe_ingredient.ingredient.unit }}</p>
        {% endfor %}
    </div>

{% endblock %}

recipe/templates/recipe/recipes_home.html
{% extends 'recipe/layout.html' %}
{% load static %}


{% block title%} 
    Home 
{% endblock %}

{% block content %}
    <h1 class="mt-3 text-center mb-5 text-light">
        All of our amazing Recipes
    </h1>

    {% for recipe in object_list %}
    <div class="card mb-3" style="max-width: 720px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ recipe.name }}</h5>
              <p class="card-text">{{ recipe.description }}</p>
              <a href="recipe/{{ recipe.id }}" class="btn btn-outline-warning">View Details</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
{% endblock %}

recipe/templates/recipe/search.html
{% extends 'recipe/layout.html' %}

{% block title %} Search {% endblock %}

{% block content %}
    <div class="text-light">
        <h1>Search</h1>
        <form action="{% url 'search' %}" method="GET">
            {{ form }}
            <input type="submit" value="Search" class="btn btn-warning btn-lg m-0">
        </form>

        {% if error_message %}
        <div class="alert alert-danger mt-3" role="alert">
            {{ error_message }}
          </div>          
        {% endif %}


        {% if recipes %}
            {{ recipes|safe }} 
        {% endif %}
    </div>
{% endblock %}

recipe/templates/recipe/success.html
{% extends 'recipe/layout.html' %}

{% block title %}
    Success
{% endblock %}

{% block content %}

    <h1 class="text-light mt-2">Success</h1>

    <div class="login-form m-3 p-3">
        <p>You have been successfully logged out</p>
        <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
    </div>

{% endblock %}
```